version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  # redis_2:
  #   image: "redis:alpine"
  #   ports:
  #    - "6380:6379"
  node_1:
    tty: true
    build: ./node
    environment: 
      - DB_HOST=db_1
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=secret
      - SELF_URL=node_1:9000
      - PORT=9000
    depends_on: 
      - db_1
    ports:
      - "9100:9000"
      - "3100:3000"
  db_1:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
  node_2:
    build: ./node
    environment: 
      - DB_HOST=db_2
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=secret
      - SELF_URL=node_2:9000
      - PORT=9000
    depends_on: 
      - db_2
    ports:
      - 9200:9000
  db_2:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
  node_3:
    build: ./node
    environment: 
      - DB_HOST=db_3
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=secret
      - SELF_URL=node_3:9000
      - PORT=9000
    depends_on: 
      - db_3
    ports:
      - 9300:9000
  db_3:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  pool:
    tty: true
    build: ./pool
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SELF_URL=pool:9000
      - PORT=9000
    ports:
      - "3000:3000"
      - "5000:9000"
    depends_on:
      - redis
  # pool_2:
  #   tty: true
  #   build: ./pool
  #   environment: 
  #     - REDIS_HOST=redis_2
  #     - REDIS_PORT=6379
  #     - SELF_URL=pool_2:9000
  #     - PORT=9000
  #   ports:
  #     - "3500:3000"
  #     - "5100:9000"
  #   depends_on:
  #     - redis
